import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
from evds import evdsAPI
from datetime import datetime, date, timedelta
from dateutil.relativedelta import relativedelta
import urllib3
import requests
from bs4 import BeautifulSoup
import io
import google.generativeai as genai

# --- KÜTÜPHANE KONTROLÜ ---
try:
    import matplotlib.pyplot as plt
    HAS_MATPLOTLIB = True
except ImportError:
    HAS_MATPLOTLIB = False

try:
    import xlsxwriter
    HAS_XLSX = True
except ImportError:
    HAS_XLSX = False

# --- YENİ: PDF KÜTÜPHANE KONTROLÜ ---
try:
    from fpdf import FPDF
    HAS_FPDF = True
except ImportError:
    HAS_FPDF = False

# SSL Hatalarını Sustur
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# --- AYARLAR ve GÜVENLİK (SECRETS) ---
MY_API_KEY = st.secrets.get("EVDS_KEY", None)
GEMINI_API_KEY = st.secrets.get("GEMINI_KEY", None)

# --- Sayfa Ayarları ---
st.set_page_config(page_title="PNX | Procurement Nexus", layout="wide", page_icon="💠")

# --- CSS Tasarım ---
st.markdown("""
    <style>
    .kutu, .kutu-enerji { padding: 15px; border-radius: 10px; margin-bottom: 12px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
    .kutu { background-color: #f8f9fa !important; border-left: 6px solid #1E3D59 !important; color: #1E3D59 !important; }
    .kutu-enerji { background-color: #fffcf5 !important; border-left: 6px solid #F39C12 !important; color: #1E3D59 !important; }
    .kutu *, .kutu-enerji *, .kutu b, .kutu-enerji b { color: #1E3D59 !important; }
    .pozitif { color: #27AE60 !important; font-weight: bold; font-size: 18px; }
    .negatif { color: #C0392B !important; font-weight: bold; font-size: 18px; }
    .stLinkButton a { color: #1E3D59 !important; font-weight: bold !important; text-decoration: none; }
    div[data-testid="stNumberInput"] label { font-size: 13px !important; color: #333 !important; }
    .badge-live { background-color: #27AE60; color: white !important; padding: 2px 6px; border-radius: 4px; font-size: 10px; font-weight: bold; vertical-align: middle; }
    .badge-tcmb { background-color: #1E3D59; color: white !important; padding: 2px 6px; border-radius: 4px; font-size: 9px; font-weight: bold; vertical-align: middle; margin-left: 5px; }
    .badge-est { background-color: #F39C12; color: white !important; padding: 2px 6px; border-radius: 4px; font-size: 9px; font-weight: bold; vertical-align: middle; margin-left: 5px; }
    div[data-testid="stDateInput"] { width: 100% !important; }
    .stButton button { width: 100%; border-radius: 5px; font-weight: bold; }
    </style>
    """, unsafe_allow_html=True)

# --- PDF SINIF TANIMI ---
if HAS_FPDF:
    class PNXReport(FPDF):
        def header(self):
            self.set_font('Arial', 'B', 12)
            self.cell(0, 10, 'TAV AIRPORTS | PNX PROCUREMENT REPORT', 0, 1, 'C')
            self.ln(5)
        def footer(self):
            self.set_y(-15)
            self.set_font('Arial', 'I', 8)
            self.cell(0, 10, f'Page {self.page_no()} | Generated by Jarvis', 0, 0, 'C')
else:
    class PNXReport: pass

# --- YARDIMCI FONKSİYONLAR ---
def render_svg_logo():
    return """
    <svg width="100%" height="auto" viewBox="0 0 280 70" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="0%">
          <stop offset="0%" style="stop-color:#1E3D59;stop-opacity:1" />
          <stop offset="100%" style="stop-color:#2C3E50;stop-opacity:1" />
        </linearGradient>
      </defs>
      <path d="M40 35 L70 35" stroke="#27AE60" stroke-width="2" />
      <path d="M40 35 L30 15" stroke="#27AE60" stroke-width="1" />
      <path d="M40 35 L30 55" stroke="#27AE60" stroke-width="1" />
      <polygon points="40,15 57,25 57,45 40,55 23,45 23,25" fill="#1E3D59" stroke="#27AE60" stroke-width="2" />
      <text x="75" y="32" font-family="Verdana" font-weight="900" font-size="28" fill="#1E3D59" letter-spacing="-1">COST NEXUS</text>
      <text x="75" y="50" font-family="Arial" font-size="11" fill="#888" font-weight="bold" letter-spacing="1">PROCUREMENT</text>
      <text x="162" y="50" font-family="Arial" font-size="11" fill="#27AE60" font-weight="bold" letter-spacing="1">VISION</text>
    </svg>
    """

def tr_fmt(deger):
    try:
        if pd.isna(deger) or deger is None: deger = 0.0
        s = "{:,.2f}".format(float(deger))
        return s.replace(",", "X").replace(".", ",").replace("X", ".")
    except: return "0,00"

def safe_float(val):
    try:
        if val is None or pd.isna(val): return 0.0
        return float(val)
    except: return 0.0

# --- SÖZLEŞME AĞIRLIK MANTIĞI ---
def get_auto_weights(contract_type):
    w = {
        "mix": 0, "tufe": 0, "ufe": 0, "hufe": 0,
        "iscilik": 0, "usd": 0, "eur": 0, "altin": 0,
        "benzin": 0, "dizel": 0, "brent": 0, "abd": 0, "eu_inf": 0
    }
    if contract_type == "Personel Taşımacılık":
        w["dizel"] = 35; w["iscilik"] = 40; w["tufe"] = 25
    elif contract_type == "Yiyecek-İçecek Hizmetleri":
        w["tufe"] = 40; w["iscilik"] = 40; w["hufe"] = 10; w["usd"] = 10
    elif contract_type == "Yazılım / Lisans":
        w["usd"] = 50; w["eur"] = 10; w["eu_inf"] = 20; w["tufe"] = 20
    elif contract_type == "Bilişim Sarf (Donanım)":
        w["usd"] = 100
    elif contract_type == "Güvenlik Hizmetleri":
        w["iscilik"] = 85; w["tufe"] = 10; w["hufe"] = 5
    elif contract_type == "Serzan'ın Klasiği (TÜFE+ÜFE)":
        w["mix"] = 100
    else: 
        w["tufe"] = 30; w["iscilik"] = 30; w["usd"] = 20; w["eur"] = 10; w["hufe"] = 10
    return w

# --- ASGARİ ÜCRET HESAPLAYICI ---
def get_asgari_ucret_degisim(d_start, d_end):
    maas_tablosu = [
        (date(2026, 1, 1), 28732.0),
        (date(2025, 7, 1), 22102.0),
        (date(2025, 1, 1), 22102.0),
        (date(2024, 1, 1), 17002.12),
        (date(2023, 7, 1), 11402.32),
        (date(2023, 1, 1), 8506.80),
        (date(2022, 7, 1), 5500.35),
        (date(2022, 1, 1), 4253.40),
        (date(2021, 1, 1), 2825.90)
    ]
    def get_val(tarih):
        for baslangic, ucret in maas_tablosu:
            if tarih >= baslangic: return ucret
        return 2825.90 
    ucret_start = get_val(d_start)
    ucret_end = get_val(d_end)
    degisim = ((ucret_end - ucret_start) / ucret_start) * 100 if ucret_start > 0 else 0.0
    return degisim, ucret_start, ucret_end

# --- YENİ: AVRUPA ENFLASYON (EU HICP) ÇEKİCİ ---
@st.cache_data(ttl=3600)
def get_eu_inflation():
    """Sir, 2026 Ocak Avrupa Bölgesi HICP beklentisi %2.35 olarak simüle edilmiştir."""
    return 2.35

# --- GOOGLE SHEET H-ÜFE ÇEKİCİ ---
@st.cache_data(ttl=600)
def get_google_sheet_data():
    try:
        sheet_url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRKKPo73sRdzL227kxw9PRvtd6teIyu74v0bw4NCZUCDmJBXgKxZ3AHYmD4zrkalxVgkOSc1lK6p7PF/pub?output=csv"
        df = pd.read_csv(sheet_url)
        df.columns = df.columns.str.strip()
        df['Tarih'] = pd.to_datetime(df['Tarih'], format='%Y-%m-%d', errors='coerce').dropna()
        return df
    except: return pd.DataFrame()

# --- DİĞER VERİ ÇEKME FONKSİYONLARI ---
@st.cache_data(ttl=3600)
def guncel_akaryakit_cek():
    url = "https://www.doviz.com/akaryakit-fiyatlari/istanbul-avrupa"
    headers = {'User-Agent': 'Mozilla/5.0'}
    fiyatlar = {"benzin": 44.50, "motorin": 45.30}
    try:
        response = requests.get(url, headers=headers, timeout=10)
        soup = BeautifulSoup(response.content, "html.parser")
        table = soup.find('table')
        if table:
            cols = table.find('tbody').find('tr').find_all('td')
            fiyatlar["benzin"] = float(cols[1].text.replace('₺', '').strip().replace(',', '.'))
            fiyatlar["motorin"] = float(cols[2].text.replace('₺', '').strip().replace(',', '.'))
    except: pass
    return fiyatlar

@st.cache_data(ttl=300)
def canli_piyasa_cek():
    sonuclar = {"USD": 0.0, "EUR": 0.0, "ALTIN": 0.0}
    try:
        ticker = yf.download("TRY=X EURTRY=X GC=F", period="1d", progress=False)
        sonuclar["USD"] = ticker['Close']['TRY=X'].iloc[-1]
        sonuclar["EUR"] = ticker['Close']['EURTRY=X'].iloc[-1]
        sonuclar["ALTIN"] = (ticker['Close']['GC=F'].iloc[-1] / 31.1035) * sonuclar["USD"]
    except: pass
    return sonuclar

@st.cache_data(ttl=3600)
def get_tcmb_data(api_key, start_date, end_date):
    res = {"TUFE": 0.0, "UFE": 0.0, "HUFE": 0.0, "Status": False, "Msg": "Veri Yok"}
    if not api_key: return res
    try:
        evds = evdsAPI(api_key)
        start_q = (start_date - relativedelta(months=1)).strftime("%d-%m-%Y")
        end_q = end_date.strftime("%d-%m-%Y")
        df = evds.get_data(["TP.FG.J0", "TP.TUFE1YI.T1"], startdate=start_q, enddate=end_q)
        if not df.empty:
            v1, v2 = df["TP_FG_J0"].iloc[0], df["TP_FG_J0"].iloc[-1]
            res.update({"TUFE": round(((v2-v1)/v1)*100, 2), "Status": True, "Msg": "EVDS Verisi Aktif"})
    except: pass
    return res

# ============================================================================
# SOL MENÜ
# ============================================================================
with st.sidebar:
    st.markdown(render_svg_logo(), unsafe_allow_html=True)
    st.markdown("<div style='margin-bottom:20px'></div>", unsafe_allow_html=True)
    st.info("ℹ️ Merhaba Sir, finansal düğümlerin çözüldüğü yerdesiniz.")
    st.markdown("---")
    sozlesme_tipi = st.selectbox("📄 Sözleşme Türü", ["Serzan'ın Klasiği (TÜFE+ÜFE)", "Manuel Giriş", "Personel Taşımacılık", "Yiyecek-İçecek Hizmetleri", "Yazılım / Lisans", "Bilişim Sarf (Donanım)", "Güvenlik Hizmetleri"])
    tutar_giris = st.text_input("Sözleşme Tutarı (TL):", value="100.000,00")
    sozlesme_tutari = safe_float(tutar_giris.replace(".", "").replace(",", "."))
    
    # Yeni: Ekstra Mevzuat/Vergi Etkisi
    extra_tax_adj = st.number_input("⚖️ Ek Vergi/Mevzuat Etkisi (%)", value=0.0, help="2026 yılındaki vergi değişikliklerini buraya girebilirsiniz.")
    
    auto_weights = get_auto_weights(sozlesme_tipi)

# ============================================================================
# ANA EKRAN - ÜST KISIM
# ============================================================================
if 'ss_start' not in st.session_state: st.session_state.ss_start = date.today() - relativedelta(years=1)
if 'ss_end' not in st.session_state: st.session_state.ss_end = date.today()

with st.container(border=True): 
    st.markdown("##### 📅 Tarih Aralığı Seçimi")
    c_d1, c_d2 = st.columns(2)
    start_date = c_d1.date_input("Başlangıç", key="ss_start", format="DD.MM.YYYY")
    end_date = c_d2.date_input("Bitiş", key="ss_end", format="DD.MM.YYYY")
    d_key = f"{start_date}_{end_date}"

# Veri Köprüsü
with st.spinner("PNX Veritabanlarına Bağlanıyor..."):
    tcmb = get_tcmb_data(MY_API_KEY, start_date, end_date)
    yakit = guncel_akaryakit_cek()
    canli = canli_piyasa_cek()
    df_hufe = get_google_sheet_data()
    val_eu_inf = get_euro_inflation()

# ============================================================================
# GÖSTERGE PANELİ (DASHBOARD)
# ============================================================================
st.title("💠 Procurement Node | Financial Datum")

with st.container(border=True):
    st.subheader("📊 Piyasa Göstergeleri")
    k1, k2, k3, k4 = st.columns(4)
    # USD/TL
    with k1:
        st.markdown(f"<div class='kutu'><b>💵 USD/TL</b><br><span class='big-metric'>{tr_fmt(canli['USD'])}</span><br><span class='badge-live'>CANLI</span></div>", unsafe_allow_html=True)
    # EUR/TL
    with k2:
        st.markdown(f"<div class='kutu'><b>💶 EUR/TL</b><br><span class='big-metric'>{tr_fmt(canli['EUR'])}</span><br><span class='badge-live'>CANLI</span></div>", unsafe_allow_html=True)
    # Gram Altın
    with k3:
        st.markdown(f"<div class='kutu'><b>🥇 Gram Altın</b><br><span class='big-metric'>{tr_fmt(canli['ALTIN'])}</span><br><span class='badge-live'>CANLI</span></div>", unsafe_allow_html=True)
    # Yeni: Avrupa Enflasyonu
    with k4:
        st.markdown(f"<div class='kutu'><b>🇪🇺 EU HICP</b><br><span class='big-metric'>%{val_eu_inf}</span><br><span class='badge-est'>TAHMİNİ</span></div>", unsafe_allow_html=True)

# ============================================================================
# HESAPLAMA MOTORU
# ============================================================================
st.markdown("---")
with st.container(border=True):
    st.subheader("⚡ Enflasyon & Sepet Hesabı")
    
    # H-ÜFE Sektör Mantığı (Orijinal)
    tum_sektorler = [col for col in df_hufe.columns if col not in ['Tarih', 'Donem']] if not df_hufe.empty else ["Yüklenemedi"]
    selected_sector = st.selectbox("📋 H-ÜFE Sektör Seçimi", tum_sektorler)
    
    val_tufe = safe_float(tcmb["TUFE"])
    val_iscilik, _, _ = get_asgari_ucret_degisim(start_date, end_date)
    
    ec1, ec2, ec3, ec4, ec5 = st.columns(5)
    in_tufe = ec1.number_input("TÜFE %", value=val_tufe)
    in_iscilik = ec2.number_input("İşçilik %", value=val_iscilik)
    in_hufe = ec3.number_input("H-ÜFE %", value=15.0)
    in_eu_inf = ec4.number_input("EU Enflasyon %", value=val_eu_inf)
    in_extra = ec5.number_input("Mevzuat Etkisi %", value=extra_tax_adj)

    st.markdown("#### ⚖️ Sepet Ağırlıkları")
    w1, w2, w3, w4, w5 = st.columns(5)
    aw = auto_weights
    sw_tufe = w1.number_input("Saf TÜFE %", value=aw["tufe"])
    sw_iscilik = w2.number_input("İşçilik %", value=aw["iscilik"])
    sw_usd = w3.number_input("USD %", value=aw["usd"])
    sw_eur = w4.number_input("EUR %", value=aw["eur"])
    sw_eu = w5.number_input("EU HICP %", value=aw["eu_inf"])

    # Kur Değişimi (Simüle)
    d_usd = ((canli["USD"] - 30.0) / 30.0) * 100
    d_eur = ((canli["EUR"] - 32.0) / 32.0) * 100

    etkiler = [
        ("TÜFE", in_tufe, sw_tufe), ("İşçilik", in_iscilik, sw_iscilik),
        ("USD", d_usd, sw_usd), ("EUR", d_eur, sw_eur),
        ("EU Enflasyon", in_eu_inf, sw_eu), ("Ek Mevzuat", in_extra, 100 if in_extra > 0 else 0)
    ]
    
    zam = sum([(e[1] * e[2])/100 for e in etkiler])
    fark = sozlesme_tutari * (zam / 100)
    yeni = sozlesme_tutari + fark

    st.markdown("---")
    r1, r2, r3 = st.columns(3)
    r1.metric("Toplam Artış", f"%{zam:.2f}")
    r2.metric("Fiyat Farkı", f"{tr_fmt(fark)} TL")
    r3.metric("YENİ TUTAR", f"{tr_fmt(yeni)} TL")

# ============================================================================
# RAPORLAMA VE JARVIS AI
# ============================================================================
st.markdown("---")
c_rep, c_ai = st.columns([1, 2])

with c_rep:
    if st.button("📥 Profesyonel PDF Oluştur"):
        if HAS_FPDF:
            pdf = PNXReport()
            pdf.add_page()
            pdf.set_font("Arial", size=10)
            pdf.cell(200, 10, txt=f"Analysis Date: {datetime.now().strftime('%d.%m.%Y')}", ln=True)
            pdf.cell(200, 10, txt=f"Contract Type: {sozlesme_tipi}", ln=True)
            pdf.cell(200, 10, txt=f"Initial Amount: {tr_fmt(sozlesme_tutari)} TL", ln=True)
            pdf.cell(200, 10, txt=f"Total Increase: %{zam:.2f}", ln=True)
            pdf.cell(200, 10, txt=f"NEW TOTAL: {tr_fmt(yeni)} TL", ln=True)
            pdf_out = pdf.output(dest='S').encode('latin-1')
            st.download_button("Dosyayı İndir", pdf_out, "PNX_Hakedis_Raporu.pdf", "application/pdf")

with c_ai:
    if st.button("🧠 Jarvis Stratejik Yorum"):
        if GEMINI_API_KEY:
            genai.configure(api_key=GEMINI_API_KEY)
            model = genai.GenerativeModel("gemini-2.5-flash")
            prompt = f"Sir, {sozlesme_tipi} için %{zam:.2f} artış hesaplandı. Avrupa enflasyonu (%{in_eu_inf}) ve yerel mevzuat risklerini yorumla."
            res = model.generate_content(prompt)
            st.info(res.text)

# Grafik Modülleri (Orijinal Matplotlib Yapısı)
if HAS_MATPLOTLIB:
    with st.expander("📈 Trend ve Senaryo Analizi", expanded=True):
        fig, ax = plt.subplots(figsize=(10, 4))
        # Örnek projeksiyon çizgisi
        x_graph = ["Mevcut", "Projeksiyon"]
        y_graph = [sozlesme_tutari, yeni]
        ax.plot(x_graph, y_graph, marker='o', color='#1E3D59')
        st.pyplot(fig)
